### ISSUE TITLE
Question about timer.

### ISSUE THREAD

**Issue by Funlxy** [demikernel/demikernel#1433]
I have a small problem with the timer implementation, does the timer calculate the cpu cycle minus its own timing overhead? For example, rdtsc() takes about 20+ cycles, if I use it in my code like this: 
```rust
  #[cfg(feature = "profiler")]
  demikernel::timer!("xxx");
  do_something();
```
the output is 100 cycles, does this result minus the overhead of calling the timer itself?

**Comment by Funlxy** [comment]
The code seems wrong, the total variable has not been updated.
https://github.com/microsoft/demikernel/blob/8293d332364efdf4faa5609e4ab82310e6749bcc/src/rust/perftools/profiler/mod.rs#L241C1-L242C1

**Comment by anandbonde** [comment]
Thanks @Funlxy, for reporting this. Yes, the total computation related issue is a bug. Fortunately we don't use this feature in our pipelines. We will evaluate whether to delete this functionality if we don't intend to use it. Or, we might end up fixing this.

**Comment by anandbonde** [comment]
> I have a small problem with the timer implementation, does the timer calculate the cpu cycle minus its own timing overhead? For example, rdtsc() takes about 20+ cycles, if I use it in my code like this:
> 
>   #[cfg(feature = "profiler")]
>   demikernel::timer!("xxx");
>   do_something();
> the output is 100 cycles, does this result minus the overhead of calling the timer itself?

We use these timers as a means of comparison, so the absolute cycles that rdtscp() takes (typically constant) does not matter. Think of it like: measure with X code, measure with Y code. Both call into rdtscp() so any other difference in X and Y would show up as timer differences.
