### ISSUE TITLE
[runtime] Various Improvements on `DataBuffer`

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#173]
Description
========

We should introduce various additional fields in the `DataBuffer` abstraction:

- [X] an identifier for the memory allocator the buffer space came from.
- [ ] one that "remembers" the original length of the data allocation (i.e. before any adjust or trim), as it might be useful in the future. (Todo: Move to Catnip milestone)
- [ ] next and prev pointers for putting on lists w/o extra allocations. (Todo: Move to Catpowder milestone)
- [ ] an "extra" field that each LibOs can use for whatever it wants (we should have space for another 64 bit field in this struct before we exceed the x86 cache line size). (Todo: Move to Catpowder milestone)

Related Issues
==========
- https://github.com/demikernel/runtime/pull/22
- https://github.com/demikernel/demikernel/pull/87

**Comment by BrianZill** [comment]
This is related to existing Issue #176.

**Comment by ppenna** [comment]
@BrianZill what is the status on this?

**Comment by anandbonde** [comment]
Created follow-up issues in subsequent milestones:
#753 and #751
