### ISSUE TITLE
[tcp] Retransmit Routine Shouldn't Remove Data from Unacknowledged Queue

### ISSUE THREAD

**Issue by BrianZill** [demikernel/demikernel#195]
Description
========

The existing retransmit routine has a fatal flaw, it is removing data from the unacknowledged queue.  This breaks our logic that tracks unacknowledged data.  Instead, retransmit() should be retransmitting the data without removing it from the queue.

Since this bug is very serious, I've disabled the calling of retransmit().  This should be reenabled when this bug is fixed.

**Comment by ppenna** [comment]
Hello @BrianZill, may we now close this bug?

**Comment by BrianZill** [comment]
Yes, this Issue was fixed in PR #374.
