### ISSUE TITLE
[tcp] Implement FIN Retransmission

### ISSUE THREAD

**Issue by BrianZill** [demikernel/demikernel#203]
Current code handles initial transmission of FIN by representing FIN as a zero-length buffer on the unsent queue and having the send code (both immediate and background) know to set the FIN bit on the segment when sending this buffer.  The zero-length buffer is then   placed on the unacknowledged (a.k.a. retransmission) queue.

The retransmission code needs to recognize the FIN marker on the unacknowledged queue and retransmit it.  Both the retransmission code and the regular send code should also be able to coalesce the FIN bit onto the last data packet.

**Comment by ppenna** [comment]
Hello @BrianZill, may we now close this bug?

**Comment by BrianZill** [comment]
Yes, we can close this.  The main part of this Issue was fixed in PR #374.  The coalescing part mentioned in the second paragraph is also mentioned in Issue #198 and should be fixed before that one is closed.
