### ISSUE TITLE
[catnip] `MemoryPool::alloc_mbuf` Function Makes Incorrect Allocation Size Comparison

### ISSUE THREAD

**Issue by BrianZill** [demikernel/demikernel#272]
Description
========

Currently in catnip's [`MemoryPool::alloc_mbuf`](https://github.com/demikernel/demikernel/blob/f40362c5110348327dc9eea3b11ab588e36ee2b3/src/rust/catnip/runtime/memory/mempool.rs) function there is[ a check to see "if allocated buffer is big enough" that compares the desired size (a `usize` taken `as u16`) against the actually allocated buffer size](https://github.com/demikernel/demikernel/blob/f40362c5110348327dc9eea3b11ab588e36ee2b3/src/rust/catnip/runtime/memory/mempool.rs).  This check will yield bogus results for cases where the desired size is greater than `u16::MAX` but less than `u16::MAX` + the actually allocated buffer size.

The correct check would promote the actually allocated buffer size from a u16 to a usize and perform the check against the two usizes.

**Comment by ppenna** [comment]
@BrianZill could you add to the description of this issue the permalink for the concerned code?

Thanks!

**Comment by BrianZill** [comment]
I've added permalinks.

This is a low priority bug, as we should never attempt to call alloc_mbuf with such a size.
