### ISSUE TITLE
[runtime] I/O Descriptors Table Should Store Structured Information on I/O Queues

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#293]
Context
======

Currently in the I/O queue descriptors table we store raw information on I/O queues.

For instance, we currently store I/O Queue types as `u32`: https://github.com/demikernel/demikernel/blob/d7db6e2ebc7933643af372d117fe470e748e0294/src/rust/runtime/queue/mod.rs#L30-L33

While functional, this may enable erroneous information to be inserted into the table.

Proposed Solution
=============

We should store structured information on the I/O queue descriptors table.

**Comment by iyzhang** [comment]
I believe this was fixed with #486

**Comment by ppenna** [comment]
Indeed it was.
