### ISSUE TITLE
Running Demikernel (Catnip) without Mellanox NIC

### ISSUE THREAD

**Issue by agshaw** [demikernel/demikernel#317]
One of the design goals is to Offer Portability across multiple devices. However I see that the implementation of Catnip Libos requires Mellanox NIC. Going through your [paper](https://irenezhang.net/papers/demikernel-sosp21.pdf), if I understand correctly, the requirement around Mellanox NIC was to facilitate the comparison of Catnip with Caladan. So, it should be possible to run Demikernel over DPDK with Non Mellanox NIC.

What changes do I have to make to achieve this? It would be really great if you could help me point in the right direction.

**Comment by ppenna** [comment]
Hello @agshaw, thanks for the interest on the project.

To get Demikernel running on a different NIC, you have to basically change device dependent under `src/rust/catnip/runtime`.

I know that there are other folks in the slack community, so I invite you to join us there.

Finally, I am changing the label of this issue to question, once the Issue template for enhancement was skipped.

**Comment by agshaw** [comment]
Thank you @ppenna 
I have joined the slack channel and will follow up on the rest there.

**Comment by LeiiY** [comment]
does it solved now ?
