### ISSUE TITLE
[question] Up to date Benchmark

### ISSUE THREAD

**Issue by Jonas-Heinrich** [demikernel/demikernel#322]
Hi,

I am a CS student at TU Munich and want to give a seminar about demikernel. Are there any up to date echo performance numbers (e.g. echo latency benchmark) since the original demikernel paper was released? I would be especially interested in the comparison between Linux (POSIX), catcollar (io_uring backed as far as I understand), catnip and raw DPDK.

I searched within the demikernel organization as well as on the linked Microsoft website, but I unfortunately found nothing..

Best regards
Jonas

**Comment by ppenna** [comment]
Hello @Jonas-Heinrich,

I am happy that you reached out to us.

There are no updates on Catnip and Catnap (POSIX sockets backend). They still report the same performance numbers.

For performance results in Catpowder (Linux raw sockets) and Catcollar (I/O Uring) you have to run the benchmarks.

If you have questions on running these, join our slack community. There are a bunch of other students that who are also working with Demikernel.

Cheers

PS: I'm taking this issue as a question. Please close if resolved.

**Comment by Jonas-Heinrich** [comment]
Thank you for the quick response, I joined the slack channel and will look into running it if I find the time :)
