### ISSUE TITLE
[pdpix] Multiplex `demi_wait()` on Top of `demi_timedwait()`

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#323]
Context
---------

The `demi_wait()` system call is a specialization of `demi_timedwait()` - it is equivalent of waiting for an indefinite amount of time.

Proposed Solution
---------------------

We should multiplex `demi_wait()` on top of `demi_timedwait()`.

This may be possible by enforcing the following semantic on the `abstime` parameter on the latter system call:
- If `abstime` has a null value, then the `demi_timedwait()` should block until the concerned I/O queue operation completes.
- If `abstime` has a non-null value it should behave as before.

**Comment by BrianZill** [comment]
I would take this further and add an _interval_ timeout value to both `demi_wait()` and `demi_wait_any()` as we discussed in the meeting we had about this issue.  With the same semantics that a missing _interval_ means "wait forever".  And a zero _interval_ means to poll once and return immediately.

You can still multiplex all of these on a single underlying implementation by adding _now_ (in absolute time) to the _interval_ (if present) in the `demi_wait()` and `demi_wait_any()` cases before calling `demi_timedwait_any()` (which would then be the common case of all the others).

**Comment by ppenna** [comment]
We agreed to address this issue differently. See https://github.com/demikernel/demikernel/pull/333 for more details.
