### ISSUE TITLE
TCP sequence number 

### ISSUE THREAD

**Issue by fahedhijazi** [demikernel/demikernel#354]
Description
========

I had a question with respect to a test assumption here:

https://github.com/demikernel/demikernel/blob/dev/src/rust/inetstack/protocols/tcp/sequence_number.rs#L164

My intuition tells me that this line of code is incorrect.

I logged the output for when the first iteration of the loop and got the following output:

```
current: 0, next: 1
current: 0, current+half: 2147483648
current: 0, next+half: 2147483649
```

Since both current and next+half are within the 32 bit range, it seems to me that next+half > current and not the opposite. Not sure if I'm missing an internal detail.

I made the following changes and it seems to work correctly now:

```
    #[inline]
    fn lt(&self, other: &Self) -> bool {
        ((self.value - other.value) as i32) < 0
    }

    #[inline]
    fn gt(&self, other: &Self) -> bool {
        other < self
    }
```
Similar changes would be necessary for the le and ge variants.

Expected Behavior
============

Distinguishing between comparing ordinal values vs whether something exists within a window.

Related Issues
==========

Similar implementations:

seastar https://github.com/scylladb/seastar/blob/bf1db44acc46c98d5be6f40bd09133d151739fbf/include/seastar/net/tcp.hh#L223
gvisor https://github.com/google/gvisor/blob/d0ae59368d8a6c4e668301f0229d6329db52be18/pkg/tcpip/seqnum/seqnum.go#L26
mtcp https://github.com/mtcp-stack/mtcp/blob/0463aad5ecb6b5bca85903156ce1e314a58efc19/mtcp/src/include/tcp_in.h#L40

**Comment by ppenna** [comment]
@BrianZill could you help here?

**Comment by BrianZill** [comment]
@fahedhijazi, can you be clearer as to what you think is wrong here?  The sequence number space wraps around.  So "<" and ">" are only "intuitive" if the numbers being compared are in the same "half" (i.e., 2^31) of the sequence number space.

Specifically,
for current = 0, next = 1, and half = 2147483648 (this is 2^31),
current < half is true (i.e., 0 < 2147483648)
current > next + half is also true (it may not be "intuitive", but 0 > 2147483649 as 2147483649 is more than 2^31 "away" from zero and thus has "wrapped around" to be less than 0).

**Comment by fahedhijazi** [comment]
Isn't it supposed to wrap at 2^32? why 2^31 when it is an unsigned value?

**Comment by fahedhijazi** [comment]
> but 0 > 2147483649 as 2147483649 is more than 2^31 "away" from zero and thus has "wrapped around"

my confusion is I don't believe this aligns with the RFC definition. The RFC allows for values of 0..2^32-1, when a value exceeds 2^32-1, it wraps around back to 0. I couldn't find a reference that considers 2^31 as having wrapped around. The only case where you want to consider wrapping around is during a sliding window check where the end of the range has wrapped, but I don't think it applies when just doing comparison checks on 2 arbitrary numbers.

**Comment by BrianZill** [comment]
> Isn't it supposed to wrap at 2^32? why 2^31 when it is an unsigned value?

Yes, it numerically "wraps" at the value of 2^32.  But 2^31 is the halfway point.  Think of any arbitrary point in the sequence number space, and you should have half of the total sequence number space as "less than" that, and the other half as "greater than" that.

I.e., given a point X in the sequence number space:

(X - 2^31) < X < (X + 2^31)

with the caveat that, due to 2's complement arithmetic being used in modern CPUs, that's actually:
(X - (2^31 - 1)) < X < (X + 2^31)

The loop in the "wrap_around" test you cited essentially checks this for all X in TCP's sequence number space.

**Comment by BrianZill** [comment]
> > but 0 > 2147483649 as 2147483649 is more than 2^31 "away" from zero and thus has "wrapped around"
> 
> @BrianZill [...] The only case where you want to consider wrapping around is during a sliding window check where the end of the range has wrapped, but I don't think it applies when just doing comparison checks on 2 arbitrary numbers.

Yes, it applies to all comparison checks on 2 arbitrary sequence numbers.  The code has to account for the sequence number space wrapping at any time.  That's actually the whole point behind these special definitions of "less than" and "greater than" for sequence numbers.

The comparisons find the difference between the two numbers as an unsigned 32-bit value.  If the difference is more than half (2^31), then the high bit will be set, and converting that unsigned 32-bit value to a signed 32-bit value will result in a negative number.  And thus comparing it to zero will result in a boolean corresponding to whether the original two numbers were "less than" or "greater than" (depending upon which comparison you made with zero) each other.

**Comment by BrianZill** [comment]
@fahedhijazi, if the above comment(s) answers your question, please close this Issue.
