### ISSUE TITLE
Where's the co_await support?

### ISSUE THREAD

**Issue by unicomp21** [demikernel/demikernel#355]
Context
======

Why not support co_await?  Like seastar?

**Comment by ppenna** [comment]
Hello @unicomp21 I don't follow your question. Could you please add some references?

**Comment by unicomp21** [comment]
@ppenna being able to write code using co_await doesn't make sense?  I'm assuming the c# bindings will support await, right?  Why not c++ as well?

https://github.com/chriskohlhoff/asio/search?q=co_await

**Comment by unicomp21** [comment]
https://github.com/scylladb/seastar/search?q=co_await

**Comment by ppenna** [comment]
Thanks for the detials @unicomp21. Now I got the whole context of this question. Let me reach out to the core team about this.

**Comment by unicomp21** [comment]
https://github.com/search?q=org%3Aboostorg+co_await&type=code

**Comment by ppenna** [comment]
Closing this because it is out of scope of the Demikernel engineering team. Note however that contributions from the community are always welcomed.
