### ISSUE TITLE
[pdpix] Remote Address Is Not Set In `demi_accept_result_t`

### ISSUE THREAD

**Issue by ArchangelSDY** [demikernel/demikernel#364]
Description
========

The `addr` in `demi_accept_result_t` seems always to be zero in an accept result. Is this a bug or am I doing this wrong? What's the correct way to obtain remote addr?

How to Reproduce
=============

1. `listen` and `accept`.
2. `wait`
3. Check `qr.qr_value.ares.addr`.

Screenshots
=========

Expected Behavior
============

Should be able to get a non-null remote addr after `accept`.

Related Issues
==========

- https://github.com/demikernel/demikernel/issues/402

## Updates

All network LibOSes fill in the `demikernel_qresult_t` with zeros:

https://github.com/demikernel/demikernel/blob/f1e518e1b8400b7934a27ba2cb595137954d34a6/src/rust/catcollar/mod.rs#L404-L418

https://github.com/demikernel/demikernel/blob/f1e518e1b8400b7934a27ba2cb595137954d34a6/src/rust/catnap/mod.rs#L391-L405

https://github.com/demikernel/demikernel/blob/f1e518e1b8400b7934a27ba2cb595137954d34a6/src/rust/catnap/mod.rs#L391-L405

https://github.com/demikernel/demikernel/blob/f1e518e1b8400b7934a27ba2cb595137954d34a6/src/rust/catpowder/interop.rs#L31-L45

**Comment by ppenna** [comment]
@ArchangelSDY could you please share what LibOS you are using?

**Comment by ArchangelSDY** [comment]
@ppenna I'm using catnip.
