### ISSUE TITLE
[test] UDP ping pong test times out and reports failed

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#409]
## Description

Unlike the TCP ping pong test, the UDP ping pong server loops forever and is killed after 30 seconds by the timeout. This produces an error code 124, which the testing scripts take to mean failure of the ping pong test. The client runs for 64 iterations and exits.

## How to Reproduce

1. Compile all rust examples 
2. Run `make test-system-rust LIBOS=catnap TEST=udp-ping-pong RUST_BACKTRACE=full CONFIG_PATH=/demikernel/config.yaml ARGS='--server 198.19.200.1:12345 198.19.200.2:23456'` and same for client.
3. See the server exit with code 124, which is the Linux timeout code

## Expected Behavior

A clean exit with no error code

## Related Issues

Link related issues here.

**Comment by ppenna** [comment]
@iyzhang the server won't exit, because it runs an infinite loop. The behavior that you described is the expected one. Currently in our UDP tests we should check exit status of client only.

**Comment by iyzhang** [comment]
Yup, that makes sense. I will close the bug.
