### ISSUE TITLE
[catpowder] TCP System Tests Failing on Bare Metal

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#433]
## Description

TCP ping pong and push pop tests fail on bare metal tests for both debug and release builds. 

## How to Reproduce

1. Run TCP system tests via azure tables script: `python3 ../tools/azure_tables.py --server prometheus1 --client prometheus2 --server-addr 198.19.200.1 --client-addr 198.19.200.2 --test-system --libos catpowder --branch dev --repository /demikernel/testing/demikernel --config-path /demikernel/config.yaml --connection
-string XXX --table-name prometheus`

## Log files

[client.stderr.txt](https://github.com/demikernel/demikernel/files/10453202/client.stderr.txt)
[server.stderr.txt](https://github.com/demikernel/demikernel/files/10453203/server.stderr.txt)

## Expected Behavior

Tests should pass without error

## Related Issues

Link related issues here.

**Comment by ppenna** [comment]
@iyzhang this looks like Linux is dropping the package. have you added the following rule to the iptables?

```bash
sudo iptables -A OUTPUT -p tcp -o $MLX_IFACE_NAME --tcp-flags RST RST -j DROP
```

**Comment by iyzhang** [comment]
I also wonder if we shouldn't just issue this command at the beginning of every test just to be sure that it is set. I think it would make our tests more robust.

**Comment by ppenna** [comment]
@iyzhang I don't think that is a good idea. The "user" should be aware of any changes in security policies.

**Comment by iyzhang** [comment]
Yeah, that is true. I meant more on our testing machines, which are specifically running a suite of tests. We could set it back at the end of the test.

**Comment by ppenna** [comment]
Removed myself from the issue and marked it as "TODO" because I cannot confirm this issue.

**Comment by ppenna** [comment]
Closing this issue, because it has been inactive for longer than a month.
