### ISSUE TITLE
[catmem] Pipe Push Pop Test Fails on Bare Metal

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#434]
## Description

The catmem pipe push pop test fails on bare metal for both debug and release builds with an error: 
```
thread 'main' panicked at 'failed to open memory queue: "failed to create shared memory region"', examples/rust/pipe-push-pop.rs:99:19
```

## How to Reproduce

1. Run catmem pipe push pop test

## Log Files

[client.stderr.txt](https://github.com/demikernel/demikernel/files/10453225/client.stderr.txt)
[server.stderr.txt](https://github.com/demikernel/demikernel/files/10453226/server.stderr.txt)

## Expected Behavior

Passed tests without error.

**Comment by ppenna** [comment]
@iyzhang from the logs provided, this looks like that some previous run in your machine has messed up with the file system state. Have you checked if there is any dangling shared memory region in "/dev/shm" ?

**Comment by iyzhang** [comment]
I can check but these tests just run automatically after pipe-ping-pong, which always pass, so there must be some cleanup that isn't happening between the two tests.

**Comment by ppenna** [comment]
Removed myself from the issue and marked it as "TODO" because I cannot confirm this issue.

**Comment by ppenna** [comment]
Closing this issue, because it has been inactive for longer than a month.
