### ISSUE TITLE
Working with raw Ethernet frames

### ISSUE THREAD

**Issue by m-kru** [demikernel/demikernel#448]
Does demikernel allow working with raw Ethernet frames? I mean both standard frames and jumbo frames.

**Comment by BrianZill** [comment]
What do you mean by "working"?

If you mean "uses", our inetstack code (as currently implemented) runs over Ethernet (either frame size), composing the Ethernet frames when sending and parsing the Ethernet frames when receiving.

If you mean "exposes" (as in presents a raw Ethernet frame interface to the user), we don't currently support that.  However, one could add a new LibOs that provides this functionality rather easily.

Does this answer your question?

**Comment by m-kru** [comment]
I would like to transmit, receive and process raw Ethernet frames. From your answer I guess it is currently not possible, isn't it?

**Comment by m-kru** [comment]
In the examples directory you show how to work with tcp and udp. However, these are protocols that are implemented on top of the Ethernet protocol. I do not see any examples for the Ethernet. It probably that simple that you have not added it, or it  is not possible to work with raw Ethernet frames. If it is possible, then an Ethernet echo example would probably be a good start point for me.

**Comment by ppenna** [comment]
@m-kru Demikernel provides a TCP/UDP socket-like API on top of DPDK. The feature that you are asking is currently not available. Mind however, that it is possible to implement it by chopping down components of the existing stack, for instance.

**Comment by ppenna** [comment]
Closing this issue, because it has been inactive for longer than a month.
