### ISSUE TITLE
[catnap] Missing free() for queue descriptors on close()

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#491]
## Description

We currently never free queue descriptors that we allocate for sockets.

## How to Reproduce

1. Call close() on queue descriptor in catnap
2. Look up queue descriptor in qtable. 

## Expected Behavior

We should not be able to look up a queue descriptor after the libOS has closed it.

**Comment by ppenna** [comment]
@iyzhang I ACK that this is related to the following code snippet:

https://github.com/demikernel/demikernel/blob/df4255bcdc57b7456e08cdeda7016d31bffb648d/src/rust/catnap/mod.rs#L223-L233
