### ISSUE TITLE
[test] Integration Tests for TCP `async_close`

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#571]
## Context

We should have the following integration tests for TCP `async_close()`:

- [x] Attempt to asynchronously close an invalid socket. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously close a TCP socket multiple times. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously close a TCP socket that is not bound. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously close a TCP socket that is bound. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously  close a TCP socket that is listening. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously close a TCP socket that is accepting. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902
- [x] Attempt to asynchronously close a TCP socket that is connecting. 816ebe0cfaa9a8fec792edac1c4f7af5d54bb902

### Additional Test Case for Asynchronous Close Multiple Times (i)

````
sockqd = socket();
qt1 = async_close(sockqd);
qt2 = async_close(sockqd);
wait(qt1);
wait(qt2);
````

### Additional Test Case for Asynchronous Close Multiple Times (ii)

````
sockqd = socket();
qt1 = async_close(sockqd);
qt2 = async_close(sockqd);
wait(qt2);
wait(qt1);
````

**Comment by iyzhang** [comment]
I'm not sure exactly how to test this since we have no remote to connect to.

**Comment by ppenna** [comment]
> I'm not sure exactly how to test this since we have no remote to connect to.

@iyzhang this test based on tcp-close. Sync up with @anandbonde .

**Comment by iyzhang** [comment]
Ok, adding @anandbonde to this issue so we can coordinate.

**Comment by anandbonde** [comment]
> > I'm not sure exactly how to test this since we have no remote to connect to.
> 
> @iyzhang this test based on tcp-close. Sync up with @anandbonde .

Yes, that test would require 2 endpoints. The tcp-close utility does exactly this for "close". We can file an issue to enhance the tcp-close utility to use close/async_close based on an input flag; and fix it in a separate PR.

**Comment by anandbonde** [comment]
> > > > > I'm not sure exactly how to test this since we have no remote to connect to.
> > > > 
> > > > 
> > > > @iyzhang this test based on tcp-close. Sync up with @anandbonde .
> > > 
> > > 
> > > Yes, that test would require 2 endpoints. The tcp-close utility does exactly this for "close". We can file an issue to enhance the tcp-close utility to use close/async_close based on an input flag; and fix it in a separate PR.
> > 
> > 
> > I have removed that case from this issue. Irene has filed a new issue to handle this separately:
> 
> What is this issue? Could you link it here? It would be nice to put it on the list, so that we can have all tests for `async_close` listed in the same place.

Sure, Updated my comment above with the issue link.

**Comment by ppenna** [comment]
We are missing an additional test case for "asynchronous closing a socket twice". I'll update the description accordingly.
