### ISSUE TITLE
Unable to run test cases

### ISSUE THREAD

**Issue by cwdolphinbaby** [demikernel/demikernel#666]
## Context

Installed demikernel for catnip and tried to run `make test-system-rust TEST=tcp-ping-pong ARGS='--client 192.168.10.118:8080'` but command failed due to "error while loading shared libraries". 

## Question

Command executed: `sudo make test-system-rust TEST=tcp-ping-pong ARGS='--client 192.168.10.118:8080'`
Terminal output: 
```timeout 30 /home/claire/demikernel/bin/examples/rust/tcp-ping-pong.elf --client 192.168.10.118:8080
/home/claire/demikernel/bin/examples/rust/tcp-ping-pong.elf: error while loading shared libraries: 
librte_ethdev.so.23: cannot open shared object file: No such file or directory
make: *** [linux.mk:193: test-system-rust] Error 127```

**Comment by ppenna** [comment]
Hello, @cwdolphinbaby 

Please join our slack community to get an answer on this. Other external contributors there may help you.

Thanks!
