### ISSUE TITLE
[memory] Introduce a Better Abstraction for Runtime Buffers

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#86]
Description
========

We currently have two abstractions for heap-managed runtime buffers: `Bytes` and `BytesMut`.

We should have a single abstraction and keep the code base simple.

**Comment by BrianZill** [comment]
Regarding the description, this abstraction isn't just for _heap-managed_ buffers, correct?

**Comment by ppenna** [comment]
@BrianZill 

> Regarding the description, this abstraction isn't just for _heap-managed_ buffers, correct?

Both `Bytes` and `BytesMut` concern abstractions for runtime buffers that were allocated in the heap. The new `HeapBuffer` abstraction that I propose in PR #87 is a replacement for them.

**Comment by ppenna** [comment]
This enhancement was introduced in commit 8630b7faebca320f0b6056049f766cd9a0c6cd0b.
