### ISSUE TITLE
[catnap] `dmtr_accept` Always Returns Zero `QToken`

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#91]
Description
========

Redis calls dmtr_accept twice in a row and gets 0 back as the qtoken both times. Specifically the following events happen:
1. Redis calls dmtr_accept on the listening socket -> returns qt = 0
2. Redis calls dmtr_wait_any(qts = {0}) -> returns with a new connection
3. Redis calls dmtr_accept on the listening socket -> returns qt = 0
4. Redis calls dmtr_pop on the new connection socket -> returns qt = 1
5. Redis calls dmtr_wait_any(qts = {0, 1}) -> error "invalid queue token"

I assume something went wrong where the second call to dmtr_accept was not allocated a new queue token (based on the fact that the pop returns qtoken = 1 and it should probably be 2).

**Comment by ppenna** [comment]
@iyzhang 

I cannot confirm this issue.

I've written a test that exercises the scenario that you detailed, and it runs fine.

Here is the server-side log that I got:

```
TRACE [demikernel::catnap] socket() domain=2, type=1, protocol=0
TRACE [demikernel::catnap] bind() qd=QDesc(0), local=Ipv4Endpoint { addr: 10.2.0.6, port: Port16(12345) }
TRACE [demikernel::catnap] listen() qd=QDesc(0), backlog=16
TRACE [demikernel::catnap] accept(): qd=QDesc(0)
TRACE [demikernel::catnap] wait_any2() [QToken(0)]
TRACE [demikernel::catnap::futures::accept] connection accepted (4)
TRACE [demikernel::catnap] accept(): qd=QDesc(0)
TRACE [demikernel::catnap] pop() qd=QDesc(1)
TRACE [demikernel::catnap] wait_any2() [QToken(0), QToken(1)]
TRACE [demikernel::catnap::futures::pop] data received (64 bytes)

[log continues]
```

I've submitted PR https://github.com/demikernel/demikernel/pull/92, to add this test to our regression suite.

Please let me know if it does not reflect the use case scenario that you described.

Finally, could you please provide me a full trace log of server-side? To get it, run set the `RUST_LOG=trace` environment variable in server side, before running Redis.

Thanks!

**Comment by iyzhang** [comment]
That was just a guess on my part. Could it be an issue in the C bindings that your test doesn’t catch?

**Comment by ppenna** [comment]
@iyzhang 

It's unlikely, but I have C binding tests on the Queue of PRs. I shall submit them in the next week or so.

Meanwhile, could you place the logs here? I suspect that the queue token becomes invalid because there is an interleaved operation on it going on, in between steps 4 and 5.

**Comment by ppenna** [comment]
A unit test was introduced to cover this issue in commit be8d02798f5cb63f14598ad3ad2cf8e0d3b0110b.
